// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 10.06.2025 18:54:20
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/Lenovo/CascadeProjects/allen-ralford-barkley/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Lenovo/CascadeProjects/allen-ralford-barkley/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Lenovo/CascadeProjects/allen-ralford-barkley/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Lenovo/CascadeProjects/allen-ralford-barkley/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Lenovo/CascadeProjects/allen-ralford-barkley/plugins/**/*.{js,ts,mjs}","C:/Users/Lenovo/CascadeProjects/allen-ralford-barkley/composables/**/*.{js,ts,mjs}","C:/Users/Lenovo/CascadeProjects/allen-ralford-barkley/utils/**/*.{js,ts,mjs}","C:/Users/Lenovo/CascadeProjects/allen-ralford-barkley/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Lenovo/CascadeProjects/allen-ralford-barkley/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Lenovo/CascadeProjects/allen-ralford-barkley/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Lenovo/CascadeProjects/allen-ralford-barkley/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;