// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 09.08.2025 03:09:24
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/Lenovo/Desktop/Allen Ralford Barkley/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Lenovo/Desktop/Allen Ralford Barkley/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Lenovo/Desktop/Allen Ralford Barkley/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Lenovo/Desktop/Allen Ralford Barkley/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Lenovo/Desktop/Allen Ralford Barkley/plugins/**/*.{js,ts,mjs}","C:/Users/Lenovo/Desktop/Allen Ralford Barkley/composables/**/*.{js,ts,mjs}","C:/Users/Lenovo/Desktop/Allen Ralford Barkley/utils/**/*.{js,ts,mjs}","C:/Users/Lenovo/Desktop/Allen Ralford Barkley/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Lenovo/Desktop/Allen Ralford Barkley/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Lenovo/Desktop/Allen Ralford Barkley/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Lenovo/Desktop/Allen Ralford Barkley/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;